const types = {
  FETCH_PODCASTS_START: "FETCH_PODCASTS_START",
  FETCH_PODCASTS_SUCCESS: "FETCH_PODCASTS_SUCCESS",
  FETCH_PODCASTS_ERROR: "FETCH_PODCASTS_ERROR",
  FETCH_EPISODES_START: "FETCH_EPISODES_START",
  FETCH_EPISODES_SUCCESS: "FETCH_EPISODES_SUCCESS",
  FETCH_EPISODES_ERROR: "FETCH_PODCASTS_ERROR",
};

export default types;